---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  annotations: {}
  name: "novartis"
  labels:
    app.kubernetes.io/name: "ingress-test"
    app.kubernetes.io/instance: "ingress-test"
spec:
  backend:
    serviceName: "test"
    servicePort: 80
    service:
      name: "test"
      port:
        number: 80
  rules:
  - host: "a.b.com"
    http: {}
  tls:
  - hosts:
    - "a.b.com"
status: {}
